### ISSUE TITLE
Control blog post snippet text?

### ISSUE THREAD

**Issue by sepi2048** [aldryn/aldryn-newsblog#289]
How can I control how much of the blog post snippet text that is showed in the text prev? 
And how cab I add an "read more" link instead of the default "..."

**Comment by mkoistinen** [comment]
Both of these can be done by overriding the template. For the number of words, change the '20' here:

https://github.com/aldryn/aldryn-newsblog/blob/master/aldryn_newsblog/boilerplates/bootstrap3/templates/aldryn_newsblog/includes/article.html#L42

To a number of your choosing. You can also add your Read more link by putting the following after the above-mentioned line:

````
<a href="{% namespace_url "article-detail" article.slug namespace=namespace default='' %}">Read More</a>
````

To remove the elipsis (…), you'll have to write a custom filter template tag, but it should be easy, because the internal method that Django's `truncatewords` templatetag uses, has an option, IIRC, to set what appears when text is truncated.

**Comment by mkoistinen** [comment]
Closing as question is answered.
