### ISSUE TITLE
Lead is missing CMSPlugin in editor to access bootstrap 3 plugins

### ISSUE THREAD

**Issue by MarcMueltin** [aldryn/aldryn-newsblog#396]
When editing a lead for a blog article, I have no possibility to access the same bootstrap 3 plugins (file, icon, etc.) as I can when working in a text plugin for the main article.

**Comment by mkoistinen** [comment]
This was done by design. The lead is usually used in article list views, and could be used in other places where the expected content is text, not markup.

If you would like full markup and plugin-capability, can I recommend simply using the Article's content placeholder where you have all of those capabilities? If you need to present this "lead-in" differently, consider using the aldryn-style or djangocms-style plugin to wrap this part of your article with a new style.
