### ISSUE TITLE
If the current user has no first_name / last_name author cannot be created

### ISSUE THREAD

**Issue by yakky** [aldryn/aldryn-newsblog#73]
When creating an Article with no author defined, a default author is created from the current user.
If the current user has no first_name / last_name the creation may fail if more that one user is created due to conflicting slugs

**Comment by yakky** [comment]
This is also related to #64

**Comment by mikek** [comment]
There is an option now not to create an author by setting `ALDRYN_NEWSBLOG_CREATE_AUTHOR` to `False`, but this in only a workaround, not a solution to this issue.

**Comment by mkoistinen** [comment]
I think this issue has sort of resolved itself since it was written. Not that authors can now be created without name's, but that:

1. The addon no longer breaks if there's no author defined, and
2. We now have app-level configuration about when author's get auto-generated.

I vote to close this, anyone have another view?

**Comment by intellectronica** [comment]
I agree, it's a non-issue now.
